config/routes.rb
Rails.application.routes.draw do
  # Survey takers
  passwordless_for :contacts, at: "/"
  resource :survey, only: [:show, :update]
  get "/survey/:step", to: "surveys#show", as: :survey_step
  get "/code/:id", to: "codes#show", as: :code

  # Public health agencies
  devise_for :users, path_prefix: "agency", controllers: {
    registrations: "users/registrations",
  }
  namespace :agency do
    resource :dashboard, only: [:show, :create]
    resources :contacts
  end

  # Public
  root to: "home#index"
  get '*unmatched_route', to: 'application#route_not_found'
end

app/models/agency.rb
# == Schema Information
#
# Table name: agencies
#
#  id         :bigint           not null, primary key
#  city       :string
#  county     :string
#  name       :string
#  state      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Agency < ApplicationRecord
  validates :city, presence: true
  validates :county, presence: true
  validates :name, presence: true
  validates :state, presence: true

  has_many :agency_reports, dependent: :destroy
  has_many :contacts, through: :agency_reports, dependent: :destroy
  has_many :users, dependent: :destroy
end

app/controllers/agency/contacts_controller.rb
class Agency::ContactsController < AgencyController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  def index
    @contacts = @agency.contacts.all
  end

  # GET /contacts/1
  def show
    redirect_to edit_agency_contact_path(@contact)
  end

  # GET /contact/new
  def new
    @contact = Contact.new
  end

  # GET /contact/1/edit
  def edit
  end

  # POST /contacts
  def create
    Contact.transaction do
      @contact = Contact.new(contact_params)

      if @contact.save
        @agency.contacts << @contact
        Invitation.send_test_result!(@agency, @contact)
        redirect_to agency_contacts_path, notice: "Survey invitation successfully sent."
      else
        render :new
        raise ActiveRecord::Rollback, "Survey contact failed to save"
      end
    end
  end

  # PATCH/PUT /contacts/1
  def update
    if params[:resend_invitation]
      Invitation.send_test_result!(@agency, @contact)
      return redirect_to agency_contacts_path, notice: 'Survey invitation sent again.'
    end

    if @contact.update(contact_params)
      redirect_to agency_contacts_path, notice: 'Survey contact was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /contacts/1
  def destroy
    @contact.destroy
    redirect_to agency_contacts_path, notice: 'Survey contact was successfully destroyed.'
  end

private

  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = @agency.contacts.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def contact_params
    params.require(:contact).permit(:name, :email, :phone)
  end

end

app/controllers/agency/dashboards_controller.rb
class Agency::DashboardsController < AgencyController

  def show
  end

  # Jump straight to survey
  def create
    contact = Contact.create_with(name: current_user.email).
      find_or_create_by!(email: current_user.email)

    Survey.create!(
      agency: current_user.agency,
      contact: contact,
    )

    passwordless.sign_in contact
    redirect_to survey_path
  end

end

app/controllers/agency_controller.rb
class AgencyController < ApplicationController
  before_action :require_agency!

private

  def require_agency!
    authenticate_user! && @agency = current_user.agency
  end

end

app/views/agency/dashboards/show.html.erb
<% content_for :head do %>
  <%= javascript_pack_tag 'dashboard', 'data-turbolinks-track': 'reload' %>
<% end %>

<h2><%= @agency.name %> Dashboard</h2>

<br>

<div class="field is-grouped">
  <div class="control">
    <%= link_to "Report positive test / start survey", new_agency_contact_path, class: "button is-light" %>
  </div>

  <div class="control">
    <%= link_to "View survey contacts", agency_contacts_path, class: "button is-link" %>
  </div>

  <div class="control">
    <%= button_to "View sample survey", agency_dashboard_path, class: "button is-warning" %>
  </div>
</div>

<br><br>

<div class="container">
  <p>
    <b>16</b> contacts reported total &nbsp; / &nbsp;
    <b>33</b> positive test results total
  </p>

  <p>
    <b>35</b> surveys complete out of <b>83</b> survey invitations sent
  </p>

  <p>
    <progress class="progress is-primary" value="42" max="100">42%</progress>
  </p>
</div>

<br><br><br>

<div class="container">
  <h3>Daily totals</h3>
  <div id="chart"></div>
</div>