config/routes.rb
Rails.application.routes.draw do
  # Survey takers
  passwordless_for :contacts, at: "/"
  resource :survey, only: [:show, :update]
  get "/survey/:step", to: "surveys#show", as: :survey_step
  get "/code/:id", to: "codes#show", as: :code

  # Public health agencies
  devise_for :users, path_prefix: "agency", controllers: {
    registrations: "users/registrations",
  }
  namespace :agency do
    resource :dashboard, only: [:show, :create]
    resources :contacts
  end

  # Public
  root to: "home#index"
  get '*unmatched_route', to: 'application#route_not_found'
end

app/models/survey.rb
# == Schema Information
#
# Table name: surveys
#
#  id         :bigint           not null, primary key
#  data       :jsonb
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  agency_id  :bigint           not null
#  contact_id :bigint           not null
#
# Indexes
#
#  index_surveys_on_agency_id   (agency_id)
#  index_surveys_on_contact_id  (contact_id)
#
# Foreign Keys
#
#  fk_rails_...  (agency_id => agencies.id)
#  fk_rails_...  (contact_id => contacts.id)
#
class Survey < ApplicationRecord
  belongs_to :agency
  belongs_to :contact, dependent: :destroy

  has_many :reported_contacts, class_name: "Contact", through: :survey_reports
  has_many :survey_reports, dependent: :destroy
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :require_contact!
  before_action :set_survey, only: [:show, :update]

  # # GET /surveys
  # def index
  #   @surveys = Survey.all
  # end

  # GET /surveys/1
  def show
    return redirect_to(survey_step_path('intro')) unless params.has_key?(:step)

    render params[:step]
  end

  # # GET /surveys/new
  # def new
  #   @survey = Survey.new
  # end

  # # GET /surveys/1/edit
  # def edit
  # end

  # # POST /surveys
  # def create
  #   @survey = Survey.new(survey_params)

  #   if @survey.save
  #     redirect_to @survey, notice: 'Survey was successfully created.'
  #   else
  #     render :new
  #   end
  # end

  # PATCH/PUT /surveys/1
  def update
    if @survey.update(survey_params)
      if params.has_key?(:next_step)
        return redirect_to(survey_step_path(params[:next_step]))
      else
        # go to the start of the form? ¯\_(ツ)_/¯
        return redirect_to(survey_step_path(1))
      end
    else
      redirect_to @survey, notice: 'There was a problem saving.' # TODO: this is not right
    end
  end

  # # DELETE /surveys/1
  # def destroy
  #   @survey.destroy
  #   redirect_to survey_url, notice: 'Survey was successfully destroyed.'
  # end

private

  # Use callbacks to share common setup or constraints between actions.
  def set_survey
    @survey = current_contact.survey
  end

  # Only allow a trusted parameter "white list" through.
  def survey_params
    params.require(:survey).permit(data: {})
  end

end

app/views/surveys/1.html.erb
<div data-controller="symptom-onset-date">

<%= form_for @survey, url: survey_path do |f| %>

<h3>When did you start feeling sick?</h3>
  <div class="field">
    <%= f.fields_for :data, @survey.data do |data| %>
    <div class="control">
    	<%= data.text_field :symptom_onset_date, type: "date", class: "input flatpickr", data: { target: "symptom-onset-date.instance" } %>
    </div>
    <% end %>
  </div>

  <p id="infectious-range" class="is-hidden" data-target="symptom-onset-date.text">
  Based off that date, you were likely infectious from
  <span data-target="symptom-onset-date.startDate"></span> to 
  <span data-target="symptom-onset-date.endDate"></span>.
  </p>

  <p>
  <input type="hidden" name="next_step" value="<%= params[:step].to_i + 1 %>" />
  <%= f.submit "Next: Close contacts", class: "button is-primary is-fullwidth" %>
  </p>
<% end %>

</div>

app/views/surveys/2.html.erb
<div data-controller="household contacts">

<%= form_for @survey, url: survey_path do |f| %>
<%= f.fields_for :data, @survey.data do |data| %>

<h3>Who were you in close contact with?</h3>

<p>
"Close contacts" are members of the same household, intimate partners, or
anyone you were in an enclosed space, and within 6 feet of each other for
more than 5 minutes.
</p>

<div class="field">
    <%= label_tag :residence, "Where do you reside?", class: "label" %>
    <div class="control">
      <%= data.radio_button :residence, "household", "data-action": "change->household#householdSelected", "data-target": "household.householdButton" %>
      <%= label_tag :residence_household, "House/apartment/condo", class: "radio" %> <br>
      <%= data.radio_button :residence, "group", "data-action": "change->household#groupSelected", "data-target": "household.groupButton"  %>
      <%= label_tag :residence_group, "Institution or group setting", class: "radio is-relative is-inline-block" %>
      <span class="subtext">(e.g. college dormitories, long term care facilities (nursing homes),
      group homes, correctional facilities, or a military base)</span>
    </div>
</div>

<div id="followup_household" class="is-hidden">
  <div class="field">
    <%= label_tag :address, "What is your address?", class: "label" %>
    <div class="control">
      <%= data.text_field :address_line_1, class: "input", placeholder: "Street address" %>
    </div>
    <div class="control">
      <%= data.text_field :address_line_2, class: "input", placeholder: "Apartment, suite, unit, building, floor, etc." %>
    </div>
    <div class="control">
      <%= data.text_field :city, class: "input", placeholder: "City" %>
    </div>
    <div class="control">
      <%= data.text_field :state, class: "input", placeholder: "State" %>
    </div>
    <div class="control">
      <%= data.text_field :zip, class: "input", placeholder: "Zip code" %>
    </div>
  </div>

  <p><strong>Excluding yourself</strong>, list the people in your household <strong>over the age of 18.</p>

  <div class="contacts" data-target="contacts.contacts">
    <div class="contact">
      <p class="label">Contact #<span class="contact-number">1</span></p>
      <div class="control">
        <%= data.text_field :name, class: "input", placeholder: "Name" %>
      </div>
      <div class="control">
        <%= data.telephone_field :phone, class: "input", placeholder: "Phone number" %><br>
      </div>
      <div class="control">
        <%= data.email_field :email, class: "input", placeholder: "Email address" %><br>
      </div>
    </div>
  </div>

  <p>
    <a data-action="click->contacts#addContact" class="is-link">Add contact</a>
  </p>

</div>

<div id="followup_group" class="is-hidden">

  <label class="label">Please list the institutional settings you spent time in</label>

<p>
  Please provide the name, address, and phone number of the institution.
  Please indicate which days you were in each institution or group setting.
</p>

<table class="table" id="groups" data-target="survey.groupTable">
  <thead>
    <tr>
      <th class="is-size-7">Name</th>
      <th class="is-size-7">Address</th>
      <th class="is-size-7">Telephone</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="is-paddingless"><%= text_field_tag :name, nil, class: "input is-small" %></td>
      <td class="is-paddingless"><%= email_field_tag :email, nil, class: "input is-small" %></td>
      <td class="is-paddingless"><%= telephone_field_tag :phone, nil, class: "input is-small" %></td>
    </tr>
    <tr>
      <td class="is-paddingless"><%= text_field_tag :name, nil, class: "input is-small" %></td>
      <td class="is-paddingless"><%= email_field_tag :email, nil, class: "input is-small" %></td>
      <td class="is-paddingless"><%= telephone_field_tag :phone, nil, class: "input is-small" %></td>
    </tr>
  </tbody>
  </table>

  <button data-action="click->survey#addMoreGroup" class="button is-primary is-small">Add another</button>

</div>

<br><br> <!-- bleh -->

<p class="is-hidden" data-target="household.nextHouseholdVisitors">
  <input type="hidden" name="next_step" class="next-step" value="2b" />
  <%= f.submit "Next: Household Visitors", class: "button is-primary is-fullwidth" %>
</p>

<p class="is-hidden" data-target="household.nextWorkContacts">
  <input type="hidden" name="next_step_disabled" class="next-step" value="3" />
  <%= f.submit "Next: Contacts at work", class: "button is-primary is-fullwidth" %>
</p>

</div>

<% end %>
<% end %>

app/views/surveys/3.html.erb
<h3 class="subtitle">Contacts at work</h3>

<p>
  In this section we will ask you about the type of work you do, and the close contacts you may have had with people while at work. We define a close contact at work as anyone with whom you were in an enclosed space, and within 6 feet of each other for 30 (or 5, depending on jurisdiction) minutes or more. If there are people that you reported as household contacts who were also close contacts at work, you do not need to add their information again.
</p>

<p>
  Question 1: Do you work in any of the following settings?
</p>

<p>
  Health care
  Emergency services
  Correctional facilities
  Assisted living facilities or nursing homes
  None of the above
</p>

<p>
  The goal of the above question is to distinguish between essential/non-essential personnel, which is of high importance for CHD. The idea would be that answering positively to any of the above “essential” occupations would trigger an alternative subset of questions specifically related to capturing contacts in those high exposure settings.
</p>

<p>
  IF YES to any of the above:
</p>
<p>
  Please provide your dates of works, the name and address of your place of work, well as the name and phone number of your staffing director.
</p>

<p>
  Additionally: IF YES to Healthcare OR Emergency Services:
</p>

<p>
  Did you have prolonged face-to-face contact with a confirmed case of COVID-19 while in a health care setting? 
</p>

<p>
  If YES
</p>

<p>
  Please record the date of the exposure
</p>

<p>
  What type of personal protective equipment did you use? (Check all that apply)
</p>

<p>
  Gown 
  Gloves 
  Eye protection
  surgical/medical mask
  N95 mask
  Were you present while an aerosol-generating procedure took place?
  If YES
  Please record the date of the procedure
  What type of personal protective equipment did you use? (Check all that apply)
  Gown 
  Gloves 
  Eye protection
  surgical/medical mask
  N95 mask
</p>

<p>
  IF NONE OF THE ABOVE:
  Question 2: From <autofill date range for infectious period>, did you go to work outside of your home?
</p>

<p>
  IF YES:
  Please provide the name and address of your place of work, well as the name and phone number of your staffing director.
</p>

<p>
  Please provide close contacts you had at work. These include people you work within 6 feet of, people who you had meetings with, or people you socialized with on breaks. For each individual who you were within 6 feet of for at least 30 minutes, please provide their name and telephone number.
</p>

<p>
  <%= link_to "Next step", survey_step_path(params[:step].to_i + 1), class: "button is-link" %>
</p>

app/views/surveys/4.html.erb
<h3 class="subtitle">Places you visited <i>other than work</i></h3>

<p>
In this portion of the survey we will ask you about locations you may have visited outside the home, separate from where you go to work. You will be prompted to enter details for each setting you list as a place you visited. It is sometimes easier to remember these events if you look at your calendar or receipts. If you have those available, we recommend referring to them as you answer these questions.
</p>

<p>
V0: This is a panel with radio buttons: The detailed questions listed below only pop up if you have selected an activity.
</p>

<p>
College, School and Daycare
Did you take children to school or daycare?
Do you attend a college, university, or other educational institution in person?
</p>

<p>
Recreation
Did you go to the gym or an exercise class, either indoors or outdoors?
Did you dine-in at a restaurant?
Did you socialize with friends?
Did you attend any large gatherings (>50 people) , such as rallies, concerts, or sports games?
</p>

<p>
Transit
Did you use public transportation such as the subway, buses, or street cars?
Did you travel anywhere by taxi or using a ride sharing service such as Lyft or Uber?
</p>

<p>
Religious and spiritual activities
Did you attend an in-person service at a place of worship?
Did you attend an in-person funeral? 
Did you attend any other spiritual or religious group gatherings (for example, a meditation group, a baptizing etc.)?
</p>

<p>
Receive any medical care at a clinic
Did you go to any type of healthcare setting, such as a doctor’s office, a hospital, a physiotherapy clinic, or a chiropractor?
</p>

<p>
Travel
Have you travelled recently? (Including international, out-of-state, inner-state, or extended local travel)
Have you stayed at a hotel, motel, hostel, or another similar lodging establishment? 
</p>


<p>
DETAILED QUESTIONS FOR EACH ACTIVITY (only pops up if the specific activity is selected).
</p>
<p>
College, Daycare, or school:

IF YES TO DAYCARE OR SCHOOL
Please indicate the number of daycares or schools that you dropped child(ren) off at:
Please provide which days you took your child(ren) to daycare or school.
Please provide the name and address, including city and town, of the daycare center or school:
Please provide the phone number for the daycare center or school:
While you were at the daycare or school, were you within 6 feet of another person for 10 minutes or more? Examples could be catching up with another parent or talking with a teacher or daycare worker. If so, please provide their name and telephone number if you know it.
</p>
<p>
IF YES TO College, University, educational institution: 
Please provide the name of institution:
Which days were you on campus?
Did you spend time in common areas (such as classrooms, libraries, laboratories, sporting rooms, gyms, etc.)
If yes: Please indicate which and provide any relevant location information. 
Please provide Name and Telephone number for anyone you had contact with on campus, where contact is defined as <contact definition>. Please do not include contacts previously identified in this survey.
</p>

<p>
Recreation:

If YES to gym or an exercise class: 

Did you go to an indoor place, such as a gym? If so please provide the name, address and phone number of the place you went, as well as the name and telephone numbers of contacts (people you were 6 feet or closer to for 15 minutes or longer) you did the activity with. 
Did you participate in outdoor recreation? If so please provide the name, address, and phone number of the place you went, as well as the name and telephone numbers of contacts (people you were 6 feet or closer to for 15 minutes or longer) you did the activity with. Please do not include contacts previously identified in this survey.
</p>
<p>
If YES to dine-in restaurant: 
Note to present to survey taker: “Please note that this includes only consuming food and beverage physically at the restaurant. Please do not count picking up food or take-out.”
During your infectious period <give range here>,  please indicate the number of times that you dined-in at a restaurant: 
For each restaurant, please provide the name, address, and phone number of the restaurant.
At each restaurant, did you dine with any other individuals? If so, please indicate the number of other people you had dinner in with:
For each person you had dinner with, please indicate their name and contact information. (This should autopopulate a question in the next section asking for info on each fellow diner.) Please do not include contacts previously identified in this survey.
</p>

<p>
If YES to socialize with friends:
Please state the purpose of the gathering: 
Where did the gathering occur?
Approximately how many people attended the gathering? (could have binned answers to click)
Please provide Name and Telephone number for anyone you had contact with, where contact is defined as <contact definition>. Please do not include contacts previously identified in this survey.
</p>
<p>
If YES to large gatherings (>50 people):
Please state the purpose of the gathering: 
Where did the gathering occur?
Approximately how many people attended the gathering? (could have binned answers to click)
Please provide Name and Telephone number for anyone you had contact with, where contact is defined as <contact definition>. Please do not include contacts previously identified in this survey.
</p>
Transit:
<p>
IF YES TO PUBLIC TRANSPORTATION
</p>
<p>
IF YES TO TAXI OR RIDESHARE
If you took a taxi, please give the Name and Contact Information of the driver. If you do not know this information, please provide the name of the taxi company, the time of day when you ordered the ride, as well as the pick-up and drop-off location. 

If you took Lyft or and Uber, please enter the name of your driver, as well as the date of the ride, the pick up and drop off locations, and the pick-up and drop-off times. This information should be available in the ride history section of the rideshare app. Kristin mentioned this but would be great if we can somehow have integration at some point with the rideshare apps such that notification process can move faster. Perhaps a V1 thing.

Did you share the ride with anyone else (other than the driver)? IF YES:
Please indicate the number of people other than you and the driver, who were in the care with you.
Please give the name, address, and contact information for each of these contacts. Please do not include contacts previously identified in this survey.
</p>
<p>
Religious and spiritual activities
IF YES TO in-person service in place of worship:
Please indicate the number of times that you visited a place of worship or engaged in a spiritual or religious activity in other individuals.
What dates did you attend in-person service?
Which place of worship did you visit? Please provide the address and name and phone number of a spiritual or organizational leader if available
Approximately how many people attended the gathering? (could have binned answers to click)
Please provide Name and Telephone number for anyone you had contact with, where contact is defined as <contact definition>. Please do not include contacts previously identified in this survey.
</p>
<p>
IF YES TO in-person funeral:
Please indicate the number of times that you attended an in-person funeral.
What dates did you attend?
Where was the funeral held? Please provide the address and name and phone number of a spiritual or organizational leader if available
Approximately how many people attended the funeral? (could have binned answers to click)
Please provide Name and Telephone number for anyone you had contact with, where contact is defined as <contact definition>. Please do not include contacts previously identified in this survey.
</p>
<p>
IF YES TO other in-person spiritual or religious group gatherings:
Please indicate the number of times that you attended an in-person spiritual or religious group gatherings not mentioned in previous question,
What dates did you attend?
Where were the gatherings held? Please provide the address and name and phone number of a spiritual or organizational leader if available
Approximately how many people attended the gathering? (could have binned answers to click)
Please provide Name and Telephone number for anyone you had contact with, where contact is defined as <contact definition>. Please do not include contacts previously identified in this survey.
</p>
<p>
IF YES to Medical Settings:
Please indicate the number of places that you went to receive  medical attention, including doctor’s offices, hospitals, health departments, or other clinics. Please do not include telemedicine appointments:
For each medical setting, please indicate the name, address, and phone number as well as the dates you visited on or during which you were hospitalized. Of note: if you went to a facility for COVID-19 test only, please do not the sites where you safely received drive-thru testing. (we likely would not consider it an exposure requiring tracing if the specimen was collected safely at a drive-thru facility).
</p>
Travel:
<p>
IF YES TO TRAVELLED RECENTLY
Please indicate the number of trips.
Was this travel international, out-of-state, inner-state, or extended local travel. Please select all that apply: Will have radio buttons
	International
Mode of transportation
</p>
<p>Airplane
Please input travel dates, airline, and flight number
Cruise ship
Please input travel dates, company, and room number
Train
Please input travel dates and train line
Bus
Please input travel dates and bus company
Personal Vehicle
Please input travel dates
	Within country but out-of-state
		Mode of transportation
Airplane
Please input travel dates, airline, and flight number
Cruise ship
Please input travel dates, company, and room number
Train
Please input travel dates and train line
Bus
Please input travel dates and bus company
Personal Vehicle
Please input travel dates
	Within-country and within-state
		Mode of transportation
Airplane
Please input travel dates, airline, and flight number
Cruise ship
Please input travel dates, company, and room number
Train
Please input travel dates and train line
Bus
Please input travel dates and bus company
Personal Vehicle
Please input travel dates
</p>	
<p>
IF YES TO MOTEL/HOTEL/HOSTEL/LODGING
Please indicate the number of different hotels/motels/hostels or other lodging that you stayed at.
Please provide dates of stay: 
Please provide the name of the hotel/motel/hostel:
Please provide the telephone number of the front desk:
Please provide the room number that you stayed in:
</p>
<p>
Additional Design Q’s?
What do we want to do about visits to retail locations, such as grocery stores, the post office, gas stations, clothing stores, or malls? Just ski?
</p>
<p>If Health care setting, such as a doctor’s office or a hospital
What type of clinic did you visit? Multiple choice: Doctor’s office, urgent care clinic, hospital, physiotherapist, chiropractor, naturopath, dentist, other (specify)
Which day and time did you arrive?: <use calendar and clock clicky thing>
Which day and time did you leave?: <use calendar and clock clicky thing>
</p>


<p>
  <%= link_to "Next step", survey_step_path(params[:step].to_i + 1), class: "button is-link" %>
</p>

app/views/surveys/5.html.erb
<h3 class="subtitle">Other close contacts</h3>

<p>
  Are there any additional individuals whom you remember having close contact with, which you have not reported in the previous sections? These are individuals with whom you were within 6 feet of for at least 5 minutes. If so, please select the number of additional contacts you wish to report, and give their name, address, telephone number, email, and the date that you had contact with them.
</p>

<p>
  Any additional contacts that you can recall but that you have not reported in other portions of this questionnaire? (IE contacts that you don’t necessarily have tied to a setting).
  Please provide contact name
  Please provide contact’s telephone numbe
</p>

<p>
  <%= link_to "Complete survey", survey_step_path(params[:step].to_i + 1), class: "button is-link" %>
</p>

app/views/surveys/6.html.erb
<h2 class="title">Thank you</h2>
<h3 class="subtitle is-5"><%= @survey.agency.name %></h3>

<p>
  Thank you very much for participating in this survey. Your responses to this survey will help us track the spread of the virus from person to person and prevent others from getting sick.
</p>

<p>
  We will not give your contacts any information about you, nor will we tell them that we received their information from you. We will try to reach your contacts 3 times. In the event that we are unable to reach your contacts, their information will be deleted after 14 days.
</p>

<p>
  Right now, this is our best way to stop the transmission of COVID-19, and your participation helps us towards that goal.
</p>

<p>
  Sincerely,<br>
  <%= @survey.agency.name %>
</p>

app/views/surveys/_form.html.erb
<%= form_with(model: survey, local: true) do |form| %>
  <% if survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(survey.errors.count, "error") %> prohibited this survey from being saved:</h2>

      <ul>
        <% survey.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :data %>
    <%= form.text_field :data %>
  </div>

  <div class="field">
    <%= form.label :agency_id %>
    <%= form.text_field :agency_id %>
  </div>

  <div class="field">
    <%= form.label :contact_id %>
    <%= form.text_field :contact_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form', survey: @survey %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Surveys</h1>

<table>
  <thead>
    <tr>
      <th>Data</th>
      <th>Agency</th>
      <th>Contact</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @surveys.each do |survey| %>
      <tr>
        <td><%= survey.data %></td>
        <td><%= survey.agency_id %></td>
        <td><%= survey.contact_id %></td>
        <td><%= link_to 'Show', survey %></td>
        <td><%= link_to 'Edit', edit_survey_path(survey) %></td>
        <td><%= link_to 'Destroy', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Survey', new_survey_path %>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render 'form', survey: @survey %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @survey.data %>
</p>

<p>
  <strong>Agency:</strong>
  <%= @survey.agency_id %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @survey.contact_id %>
</p>

<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>